# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078fa1ba37f498220ead4d75151054a02d26f2d40c7c76533d0c04bfc0afa3c5063ca9ee985f4222458fa18412ec88f25c9aa52d4213b84cb413a108d936b793

test:
  secret_key_base: 42d6878bce27c7d81aa3b31896a0846f838bc13448284d560d159c0e96219e302dd15de47e223e3afbb01be292efe777f3de90a47d344a045ab0e606f043b727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
